app_larvarios/urls.py
from django.conf.urls import url
from . import views

# /larvarios/

urlpatterns = [
	url(r'^$', views.index, name="index"),	
	url(r'^nuevo-ciclo/$', views.nuevo_ciclo, name="nuevo_ciclo"),	
	url(r'^cerrar-ciclo/$', views.cerrar_ciclo, name="cerrar_ciclo"),	
	url(r'^verificar-ciclo-activo/$', views.verificar_ciclo_activo, name="verificar_ciclo_activo"),	
	url(r'^parametros-agua/(?P<id>\d+)/$', views.parametros_agua, name="parametros_agua"),
	url(r'^datos-larva/(?P<id>\d+)/$', views.datos_larva, name="datos_larva"),
	url(r'^parametros-agua/guardar/$', views.parametros_agua_guardar, name="parametros_agua_guardar"),
	url(r'^datos-larva/guardar/$', views.datos_larva_guardar, name="datos_larva_guardar"),
	url(r'^filtrar-params-agua/$', views.filtrar_params_agua, name="filtrar_params_agua"),
]

unifinca/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app_general import views

urlpatterns = [    
    url(r'^$', views.form_login, name='form_login'),
    url(r'^login/$', views.validate_login, name='validate_login'),
    url(r'^logout/$', views.sign_off, name='sign_off'),
    url(r'^ajax-test/$', views.ajax_test, name='ajax_test'),
    url(r'^admin/', admin.site.urls),
    url(r'^algas/', include('app_algas.urls')),
    url(r'^dashboard/', include('app_dashboard.urls')),
    url(r'^general/', include('app_general.urls')),
    url(r'^larvarios/', include('app_larvarios.urls')),
    url(r'^maduracion/', include('app_maduracion.urls')),
    url(r'^reporte/', include('app_reportes.urls')),
]

app_larvarios/models.py
#coding: utf8
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Modulo(models.Model):
	nombre = models.CharField(max_length=10)
	departamento = models.CharField(max_length=15, null=True)

	def __str__(self):
		return '%s > %s' % (self.departamento, self.nombre)


@python_2_unicode_compatible
class Sala(models.Model):
	nombre = models.CharField(max_length=10)
	modulo = models.ForeignKey(Modulo)

	def __str__(self):
		return '%s > %s > %s' % (self.modulo.departamento, self.modulo.nombre, self.nombre)


@python_2_unicode_compatible
class Estado(models.Model):
	estado_ciclo = models.CharField(max_length=15)

	def __str__(self):
		return self.estado_ciclo


@python_2_unicode_compatible
class Estadio(models.Model):
	nombre = models.CharField(max_length=25)

	def __str__(self):
		return self.nombre


@python_2_unicode_compatible
class CicloLarva(models.Model): 
	poblacion_inicial = models.PositiveIntegerField(verbose_name='Población inicial')
	fecha_inicio = models.DateTimeField(auto_now_add=True)
	fecha_final = models.DateTimeField(null=True, blank=True)
	numero_ciclo = models.SmallIntegerField(verbose_name='Número de ciclo')
	estado = models.ForeignKey(Estado)
	sala = models.ForeignKey(Sala)

	def __str__(self):
		return 'Ciclo %d [ %s ] > %s (%s)' % (self.numero_ciclo, self.fecha_inicio, self.sala, self.estado.estado_ciclo)


@python_2_unicode_compatible
class DatosLarva(models.Model):
	fecha = models.DateField(auto_now_add=True)
	retraso = models.SmallIntegerField(verbose_name='Porcentaje de retraso', null=True, blank=True)
	mortalidad = models.SmallIntegerField(verbose_name='Porcentaje de mortalidad', null=True, blank=True)
	deformidad = models.SmallIntegerField(verbose_name='Porcentaje de deformidad', null=True, blank=True)
	poblacion = models.PositiveIntegerField(verbose_name='Población actual', null=True, blank=True)
	supervivencia = models.SmallIntegerField(verbose_name='Porcentaje de supervivencia', null=True, blank=True)
	imm = models.CharField(max_length=25, verbose_name='Índice de masa muscular', null=True, blank=True)
	estadio = models.ForeignKey(Estadio, verbose_name='Estadío (requerido)')
	ciclo_larva = models.ForeignKey(CicloLarva)

	def __str__(self):
		return str(self.fecha)

class DatoParametroAgua(models.Model):
	ciclo = models.ForeignKey(CicloLarva)
	fecha_ingreso = models.DateField(auto_now_add=True)
	ph = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='pH')
	temperatura = models.DecimalField(max_digits=5, decimal_places=2)
	oxigeno = models.DecimalField(max_digits=5, decimal_places=2)
	salinidad = models.DecimalField(max_digits=5, decimal_places=2)

	class Meta:
		ordering = ['-fecha_ingreso', 'ciclo']

app_larvarios/forms.py
#coding: utf8
from django import forms
from .models import CicloLarva, DatoParametroAgua, DatosLarva

class CicloLarvaForm(forms.ModelForm):
	class Meta:
		model = CicloLarva
		fields = '__all__'
		#widgets = { 'fecha': forms.HiddenInput() }


class DatoParametroAguaForm(forms.ModelForm):
	class Meta:
		model = DatoParametroAgua
		fields = '__all__'
		widgets = { 'ciclo': forms.HiddenInput() }

class DatosLarvaForm(forms.ModelForm):
	class Meta:
		model = DatosLarva
		fields = '__all__'
		widgets = { 'ciclo_larva': forms.HiddenInput() }

app_larvarios/views.py
#coding: utf8
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.conf import settings # Para obtener el departamento
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Sum
from django.utils import timezone

from app_general.models import OrigenAgua, Microbiologia, DatoParametroAgua as DPAG
from app_general.forms import MicrobiologiaForm, DatoParametroAguaForm as DPAForm

from .models import Modulo, Estado, CicloLarva, Sala, DatoParametroAgua, DatosLarva
from .forms import CicloLarvaForm, DatoParametroAguaForm, DatosLarvaForm

from datetime import datetime, timedelta
import json
from time import sleep

@login_required()
def index(request):
	depto = settings.DEPARTAMENTOS['l']

	# variables form_micro y consulta van a base.html
	form_micro = MicrobiologiaForm(initial={'departamento': depto})
	ultimo_mes = datetime.today() - timedelta(days=30)
	consulta1 = Microbiologia.objects.filter(departamento=depto, fecha__gte=ultimo_mes).order_by('-fecha')

	# variables form_params y consulta van a base.html
	form_params = DPAForm(initial={'departamento': depto})
	#consulta2 = DPAG.objects.filter(departamento=depto).order_by('-fecha_ingreso')
	consulta4 =  OrigenAgua.objects.all()

	# ciclos y analisis de larvas en salas
	modulos = Modulo.objects.filter(departamento=depto)

	# formulario para agregar parametros
	activo = Estado.objects.get(pk=1)
	form_ciclo = CicloLarvaForm(initial={'estado': activo})

	contexto = {
		'form_micro': form_micro,
		'form_ciclo': form_ciclo,
		'form_params': form_params,
		'datos_micro': consulta1,
		#'datos_params': consulta2,
		'datos_origen_agua': consulta4,
		'modulos': modulos,
		'depto': depto, 
	}

	return render(request, 'larvarios.html', contexto)


@login_required()
def nuevo_ciclo(request):
	if request.method == 'POST':
		form = CicloLarvaForm(request.POST)

		if form.is_valid():
			try:
				numero_ciclo = form.cleaned_data['numero_ciclo']
				sala = form.cleaned_data['sala']

				# verificar si existe un ciclo activo para esta sala
				estado_activo = Estado.objects.get(pk=1)
				existe_ciclo = CicloLarva.objects.filter(sala=sala, estado=estado_activo)

				if not existe_ciclo:
					form.save()
					return JsonResponse({'sala_id': sala.id, 'num_ciclo': numero_ciclo, 'respuesta': 'Un nuevo ciclo ha sido iniciado'})
				else:
					return JsonResponse({'respuesta': 'Ciclo %d aun está activo' % existe_ciclo[0].numero_ciclo})
				
			except Exception, e:
				return JsonResponse({'respuesta': e})
		else:
			return HttpResponse(form.errors)


@login_required()
def cerrar_ciclo(request):
	sala = Sala.objects.get(pk=request.GET.get('sala_id'))
	estado_activo = Estado.objects.get(pk=1)
	
	# Model.objects.get(pk=1): Devuelve un objeto del modelo
	# Model.objects.filter(estado='Activo'): Devuelve un queryset. Utilizar [indice] para acceder a los objetos

	ciclo_activo = CicloLarva.objects.filter(sala=sala, estado=estado_activo)
	
	if not ciclo_activo:
		#return HttpResponse('No hay ciclo')
		# No hay ciclo en la sala para cerrar
		return JsonResponse({'respuesta': 'No hay ciclo activo en esta sala'})
	else:

		#return HttpResponse('Hay ciclo')
		# Se cierra el ciclo
		estado_terminado = Estado.objects.get(estado_ciclo='Terminado')
		ciclo_activo[0].estado = estado_terminado
		ciclo_activo[0].fecha_final = datetime.today()
		ciclo_activo[0].save()

		# Aunque solo hay un ciclo activo por sala, se obtiene el objeto con .filter para utilizar 'if not ciclo_activo' ...
		# al verificar que no hay ciclos. En cambio con .get, el operador not no es soportado, en su lugar hay que utilizar Try ...
		# para manejar la excepcion 'matching query does not exist'

		return JsonResponse({'respuesta': 'El ciclo %d ha sido terminado' % ciclo_activo[0].numero_ciclo})


@login_required()
def verificar_ciclo_activo(request):
	sala = Sala.objects.get(pk=request.GET.get('sala_id'))
	estado_activo = Estado.objects.get(pk=1)
	estado_terminado = Estado.objects.get(pk=2)
	
	ciclo = CicloLarva.objects.filter(sala=sala, estado=estado_activo)

	if ciclo: # La sala tiene un ciclo activo
		return JsonResponse({'ok': True, 'num_ciclo': ciclo[0].numero_ciclo, 'class': 'btn-ciclo-activo'})
	else:     # La sala no tiene ciclo activo, se obtendra cual fue el ultimo ciclo
		# select * from ciclolarva where sala = n and estado = 'terminado' order by numero ciclo desc limit 1;
		ultimo_ciclo = CicloLarva.objects.filter(sala=sala, estado=estado_terminado).order_by('-numero_ciclo')[:1]

		if ultimo_ciclo:
			return JsonResponse({'ok': False, 'num_ciclo': ultimo_ciclo[0].numero_ciclo})
		else:
			return HttpResponse('Ningun ciclo activo')


@login_required()
def parametros_agua(request, id):	
	try:
		sala = Sala.objects.get(pk=id)
		estado_activo = Estado.objects.get(pk=1)
		ciclo = CicloLarva.objects.get(sala=sala, estado=estado_activo)
		form = DatoParametroAguaForm(initial={'ciclo': ciclo})

		ultimo_mes = datetime.today() - timedelta(days=30)
		datos_params = DatoParametroAgua.objects.filter(ciclo=ciclo, fecha_ingreso__gte = ultimo_mes).order_by('fecha_ingreso')

		return render(request, 'parametros-agua.html', {'sala': sala.nombre, 'form': form, 'id': id, 'datos_params': datos_params})
	except Sala.DoesNotExist:
		return HttpResponse('No existe la sala')
	except CicloLarva.DoesNotExist:
		return HttpResponseRedirect('/larvarios/')


@login_required()
def parametros_agua_guardar(request):
	if request.method == 'POST':
		form = DatoParametroAguaForm(data=request.POST)
		sleep(3)
		if form.is_valid():
			ultimo_objeto = form.save()

			if request.is_ajax():
				tr = '<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>' % (ultimo_objeto.fecha_ingreso, ultimo_objeto.ph, ultimo_objeto.temperatura, ultimo_objeto.oxigeno, ultimo_objeto.salinidad)
					
				resultado = {'respuesta': 'Información guardada con éxito', 'fila': tr}
				return JsonResponse(resultado)
			else:
				return HttpResponseRedirect('/larvarios/')

@login_required()
def filtrar_params_agua(request):
	filtro, tr, script = request.GET.get('filtro'), "", request.GET.get('script')

	sala = Sala.objects.get(pk=request.GET.get('idsala'))
	estado_activo = Estado.objects.get(pk=1)
	ciclo = CicloLarva.objects.get(sala=sala, estado=estado_activo)

	# Consultas para informacion de larva
	if script == 'info':
		if filtro == 'hoy':
			datos = DatosLarva.objects.filter(ciclo_larva = ciclo, fecha = timezone.now())

			for dato in datos:
				tr = '<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>' % (dato.fecha, dato.retraso, dato.mortalidad, dato.deformidad, dato.poblacion, dato.supervivencia, dato.imm, dato.estadio)

		elif filtro == 'mes':
			ultimo_mes = datetime.today() - timedelta(days=30)
			datos = DatosLarva.objects.filter(ciclo_larva = ciclo, fecha__gte = ultimo_mes)
			
			for dato in datos:
				tr = '<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>' % (dato.fecha, dato.retraso, dato.mortalidad, dato.deformidad, dato.poblacion, dato.supervivencia, dato.imm, dato.estadio)
		else: #rango
			datos = DatosLarva.objects.filter(ciclo_larva = ciclo, fecha__range = (request.GET.get('desde'), request.GET.get('hasta')))
			
			for dato in datos:
				tr = '<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>' % (dato.fecha, dato.retraso, dato.mortalidad, dato.deformidad, dato.poblacion, dato.supervivencia, dato.imm, dato.estadio)

		return JsonResponse({'respuesta': tr})


	# Consultas para calidad de agua
	if filtro == 'hoy':
		datos = DatoParametroAgua.objects.filter(ciclo = ciclo, fecha_ingreso = timezone.now())

		for dato in datos:
			tr += '<tr><th>%s</th><td>%.2f</td><td>%.2f</td><td>%.2f</td><td>%.2f</td></tr>' % (dato.fecha_ingreso, dato.ph, dato.temperatura, dato.oxigeno, dato.salinidad)

	elif filtro == 'mes':
		ultimo_mes = datetime.today() - timedelta(days=30)
		datos = DatoParametroAgua.objects.filter(ciclo = ciclo, fecha_ingreso__gte = ultimo_mes)
		
		for dato in datos:
			tr += '<tr><th>%s</th><td>%.2f</td><td>%.2f</td><td>%.2f</td><td>%.2f</td></tr>' % (dato.fecha_ingreso, dato.ph, dato.temperatura, dato.oxigeno, dato.salinidad)
	else: #rango
		datos = DatoParametroAgua.objects.filter(ciclo = ciclo, fecha_ingreso__range = (request.GET.get('desde'), request.GET.get('hasta')))
		
		for dato in datos:
			tr += '<tr><th>%s</th><td>%.2f</td><td>%.2f</td><td>%.2f</td><td>%.2f</td></tr>' % (dato.fecha_ingreso, dato.ph, dato.temperatura, dato.oxigeno, dato.salinidad)

	return JsonResponse({'respuesta': tr})


@login_required()
def datos_larva(request, id):
	try:
		sala = Sala.objects.get(pk=id)
		estado_activo = Estado.objects.get(pk=1)
		ciclo = CicloLarva.objects.get(sala=sala, estado=estado_activo)
		form = DatosLarvaForm(initial={'ciclo_larva': ciclo})

		ultimo_mes = datetime.today() - timedelta(days=30)
		datos_larva = DatosLarva.objects.filter(ciclo_larva=ciclo, fecha__gte = ultimo_mes).order_by('fecha')	

		return render(request, 'datos-larva.html', {'sala': sala.nombre, 'form': form, 'id': id, 'datos_larva': datos_larva})
	except Sala.DoesNotExist:
		return HttpResponse('No existe la sala')
	except CicloLarva.DoesNotExist:
		return HttpResponseRedirect('/larvarios/')

@login_required()
def datos_larva_guardar(request):
	if request.method == 'POST':
		form = DatosLarvaForm(data=request.POST)

		if form.is_valid():
			ultimo_objeto = form.save()

			if request.is_ajax():
				tr = '<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>' % (ultimo_objeto.fecha, ultimo_objeto.retraso, ultimo_objeto.mortalidad, ultimo_objeto.deformidad, ultimo_objeto.poblacion, ultimo_objeto.supervivencia, ultimo_objeto.imm, ultimo_objeto.estadio)
					
				resultado = {'respuesta': 'Información guardada con éxito', 'fila': tr}
				return JsonResponse(resultado)
			else:

app_larvarios/templates/datos-larva.html
{% extends "base-core.html" %}

{% block active_larvario %}active{% endblock %}
{% block description_page %} <strong>{{ sala }}</strong>: Datos de larva{% endblock %}
{% block content_page %}
	<!-- Inicio del control Tabs -->
	<div class="row">
		<div class="col s12">
			<ul class="tabs tab-demo z-depth-1 tabs-fixed-width">
				<li class="tab col s3"><a href="#tabA">Registro de datos de larva</a></li>
				<li class="tab col s3"><a href="#tabB">Datos registrados</a></li>
			</ul>
		</div>

		<div id="tabA" class="col s12 m8 l6">			
			<form action="/larvarios/datos-larva/guardar/" method="post" class="card-panel" id="form-datos-larva">
				{% csrf_token %}
				
				{{ form }}

				<div class="row">
					<div class="input-field col m8 s12 l6">
						<input type="submit" value="GUARDAR" class="waves-effect waves-light btn btn-ajax">
					</div>
				</div>		
				<br>
			</form>			
		</div>

		<div id="tabB" class="col s12">
			<br>
			 Datos de: 
            <a href="#" class="params-larva-filtro" data-value="hoy" data-idsala="{{ id }}">Hoy</a> -  
            <a href="#" class="params-larva-filtro" data-value="mes" data-idsala="{{ id }}">Hace 30 días</a>
            <hr class="style-one">
            Desde: <input type="date" class="standard params-larva-desde"> 
            Hasta: <input type="date" class="standard params-larva-hasta"> 
            <a href="#" class="params-larva-filtro" data-value="rango" data-idsala="{{ id }}">Filtrar</a>
            <hr class="style-one">			
			<input type="hidden" class="script" value="info">
			<table id="tabla-params-agua-larvarios">
				<thead>
					<tr>
						<th>Fecha</th>
						<th>Retraso</th>
						<th>Mortalidad</th>
						<th>Deformidad</th>
						<th>Población</th>
						<th>Supervivencia</th>
						<th>IMM</th>
						<th>Estadío</th>
					</tr>
				</thead>

				<tbody id="datos-larva">
					{% for dato in datos_larva %}
					<tr>
						<td>{{ dato.fecha }}</td>
						<td>{{ dato.retraso }}</td>
						<td>{{ dato.mortalidad }}</td>
						<td>{{ dato.deformidad }}</td>
						<td>{{ dato.poblacion }}</td>
						<td>{{ dato.supervivencia }}</td>
						<td>{{ dato.imm }}</td>
						<td>{{ dato.estadio.nombre }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			<br>
		</div>
	</div>
	<!-- Fin del control Tabs -->
	
{% endblock %}

app_larvarios/templates/grafico-parametros.html
{% extends "base-core.html" %}

{% block content_page %}
	
	<a href="#" class="btn btn-grafico">Ver grafico</a>	

	<p>
		<table id="datatable">
			<thead>
				<tr>
					<th></th>
					<th>pH</th>
					<th>Temp.</th>
					<th>Oxigeno</th>
				</tr>
			</thead>

			<tbody>
				{% for dict in datos %}

				<tr>
					<th>{{ dict.sala__modulo__nombre }} - {{ dict.sala__nombre }}</th>
					<th>{{ dict.PH|floatformat }}</th>
					<th>{{ dict.TEMP|floatformat }}</th>
					<th>{{ dict.OXI|floatformat }}</th>
					
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</p>

	<div class="row">
		<div id="grafico" class="col l12"></div>
	</div>

{% endblock %}

app_larvarios/templates/larvarios.html
{% extends "base.html" %}

<!-- Para definir en activo el link en el menu lateral-->
{% block active_larvario %}active{% endblock %}

{% block description_page %}
	Departamento de Larvarios
{% endblock %}

{% block collaps_title1 %}Información de Larva y Agua{% endblock %}
{% block collaps_content1 %}
	<div class="container">
		<div class="row">
			<div class="col m12 s12 l12">
				<br>
				<span style="background: #E05573; padding: 3px; color: #fff">Ciclo activo</span> | 
				<span style="background: #26a69a; padding: 3px; color: #fff">Ciclo terminado</span>
				<hr class="style-one">
				
				<table class="bordered responsive-table">
					<tbody>
						{% for modulo in modulos %}
						<tr>
							<th><h6> <strong>{{ modulo.nombre }}</strong></h6></th>

							{% for sala in modulo.sala_set.all %}
							<td>
								<a class='dropdown-button btn btn-sala' href='#' id="{{ sala.id }}" data-activates='dropdown{{ sala.id }}'>
									<i class="material-icons left">toc</i> {{ sala.nombre }}
								</a>
								<ul id='dropdown{{ sala.id }}' class='dropdown-content'>
									<li><a href="#modal{{ sala.id }}">Nuevo ciclo</a></li>
									<li><a href="#!" data-sala-id="{{ sala.id }}" class="cerrar-ciclo">Cerrar ciclo</a></li>
									<li class="divider"></li>
									<li><a href="/larvarios/parametros-agua/{{ sala.id }}/">Parámetros de agua</a></li>
									<li><a href="/larvarios/datos-larva/{{ sala.id }}/">Información de larvas</a></li>									
								</ul>
								<!-- Modal Structure -->
								<div id="modal{{ sala.id }}" class="modal">
									<div class="modal-content">
										<h4>{{ sala }}: Nuevo ciclo</h4>
										<form action="nuevo-ciclo/" method="post" class="card-panel form-nuevo-ciclo">
											{% csrf_token %}
											<label for="id_poblacion_inicial">Poblacion inicial</label>
											<input id="id_poblacion_inicial" class="comma-separated" name="poblacion_inicial" type="text" required />
										
											<label for="id_numero_ciclo">Numero ciclo:</label>
											<input id="id_numero_ciclo" class="sala{{ sala.id }}" name="numero_ciclo" type="number" required />

											<input type="hidden" id="id_fecha_final" name="fecha_final"  />
											<input type="hidden" id="id_estado" name="estado"  value="1" />
											<input type="hidden" id="id_sala" name="sala"  value="{{ sala.id }}" />

											<div class="modal-footer">
												<input type="submit" class="modal-action waves-effect waves-green btn-flat btn-ajax" value="GUARDAR">
											</div>
										</form>
									</div>
									
								</div>
							</td>
							{% endfor %}
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>	
{% endblock %}

app_larvarios/templates/parametros-agua.html
{% extends "base-core.html" %}

{% block active_larvario %}active{% endblock %}
{% block description_page %} <strong>{{ sala }}</strong>: Parámetros de agua{% endblock %}
{% block content_page %}
	<!-- Inicio del control Tabs -->
	<div class="row">
		<div class="col s12">
			<ul class="tabs tab-demo z-depth-1 tabs-fixed-width">
				<li class="tab col s3"><a href="#tabA">Registro de parámetros de agua</a></li>
				<li class="tab col s3"><a href="#tabB">Parámetros registrados</a></li>
			</ul>
		</div>

		<div id="tabA" class="col s12 m8 l6">			
			<form action="/larvarios/parametros-agua/guardar/" method="post" class="card-panel" id="form-params-agua" data-source="params-ciclos">
				{% csrf_token %}
				
				{{ form }}

				<div class="row">
					<div class="input-field col m8 s12 l6">
						<input type="submit" value="GUARDAR" class="waves-effect waves-light btn btn-ajax">
					</div>
				</div>		
				<br>
			</form>			
		</div>

		<div id="tabB" class="col s12">
			<br>
			 Datos de: 
            <a href="#" class="params-larva-filtro" data-value="hoy" data-idsala="{{ id }}">Hoy</a> -  
            <a href="#" class="params-larva-filtro" data-value="mes" data-idsala="{{ id }}">Hace 30 días</a>
            <hr class="style-one">
            Desde: <input type="date" class="standard params-larva-desde"> 
            Hasta: <input type="date" class="standard params-larva-hasta"> 
            <a href="#" class="params-larva-filtro" data-value="rango" data-idsala="{{ id }}">Filtrar</a>
            <hr class="style-one">

			<div id="grafico-params-agua" class="col l12 grafico"></div>

			<table id="tabla-params-agua-larvarios">
				<thead>
					<tr>
						<th>Fecha</th>
						<th>pH</th>
						<th>Temp.</th>
						<th>Oxigeno</th>
						<th>Salinidad</th>
					</tr>
				</thead>

				<tbody id="datos-parametros">
					{% for dato in datos_params %}
					<tr>
						<td>{{ dato.fecha_ingreso }}</td>
						<td>{{ dato.ph }}</td>
						<td>{{ dato.temperatura }}</td>
						<td>{{ dato.oxigeno }}</td>
						<td>{{ dato.salinidad }}</td>
					</tr>					
					{% endfor %}
				</tbody>
			</table>
			<br>
		</div>
	</div>
	<!-- Fin del control Tabs -->
	
{% endblock %}